name: Release dprint-plugin-cedar
on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Install dependencies
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dprint-plugin-cedar
          path: target/wasm32-unknown-unknown/release/dprint-plugin-cedar.wasm

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG_NAME: commit-${{ github.sha }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "dprint-plugin-cedar build for ${{ github.sha }}"
          files: target/wasm32-unknown-unknown/release/dprint-plugin-cedar.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
